作業目標<br>
在一個陣列中放入多屬性陣列，進一步對陣列做運算<br>
作業重點<br>
在建立結構化陣列前需要先設定屬性，在做運算時須注意資料屬性

題目:<br>
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']<br>
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']<br>
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]<br>
rank_list = [8,1,5,4,7,6,2,3]<br>
myopia_list = [True,True,False,False,True,True,False,False]<br>
1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]<br>
2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
3. 呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重


In [2]:
import numpy as np 

In [3]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [4]:
#1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
#建立name以及formats(dtype)

dt = np.dtype({'names':('Name', 'sex', 'weight', 'rank','myopia'), 'formats':('U5', 'U5', 'f', 'i','?')})

c = np.zeros(8,dtype=dt)
c['Name'] = name_list
c['sex'] = sex_list
c['weight'] = weight_list
c['rank'] = rank_list
c['myopia'] = myopia_list
c



array([('小明', 'boy', 67.5, 8,  True), ('小華', 'boy', 75.3, 1,  True),
       ('小菁', 'girl', 50.1, 5, False), ('小美', 'girl', 45.5, 4, False),
       ('小張', 'boy', 80.8, 7,  True), ('John', 'boy', 90.4, 6,  True),
       ('Mark', 'boy', 78.4, 2, False), ('Tom', 'boy', 70.7, 3, False)],
      dtype=[('Name', '<U5'), ('sex', '<U5'), ('weight', '<f4'), ('rank', '<i4'), ('myopia', '?')])

In [5]:
#2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
aver_wei = np.sum(c['weight'])
aver_wei

558.7

In [6]:
#3. 呈上題，進一步算出男生(sex欄位是boy)平均體重

aver_wei_boy = np.sum(c['weight'][c["sex"]=="boy"])
aver_wei_boy

463.09998

In [7]:
#3. 呈上題，進一步算出女生(sex欄位是girl)平均體重

In [8]:
aver_wei_girl = np.sum(c['weight'][c["sex"]=="girl"])
aver_wei_girl

95.6

In [14]:
a = np.zeros(10) #0
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
b = np.empty(10) #接近0的數
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

SyntaxError: invalid character in identifier (<ipython-input-16-eed963cafb38>, line 1)

In [17]:
a = np.random.rand(2, 3)

# astype 取整數部分
print("before change: ",a)

print("after change: ", a.astype(int) )

before change:  [[0.71100896 0.250063   0.61937793]
 [0.84344314 0.7676744  0.13983406]]
after change:  [[0 0 0]
 [0 0 0]]


In [19]:
m = 100
n = 10


np.reshape(np.linspace(10,100,6),(2,3))

array([[ 10.,  28.,  46.],
       [ 64.,  82., 100.]])