In [2]:
import numpy as np

In [3]:
#1
a = np.arange(0,21,1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [4]:
#2
b = a[::2]
b


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
#3
c = a[::3]
c

array([ 0,  3,  6,  9, 12, 15, 18])

In [9]:
c.shape,len(c),type(c)

((7,), 7, numpy.ndarray)

In [10]:
list(c)

[0, 3, 6, 9, 12, 15, 18]

In [19]:
a.tolist(),list(a)

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])