作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [1]:
import numpy as np

In [2]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
s= np.linalg.inv(array1)
ori= np.dot(array1,s)
ori

array([[1., 0.],
       [0., 1.]])

In [3]:
#2. 運用上列array計算特徵值、特徵向量?
w,v =np.linalg.eig(array1)
print('特徵值:\n',w,'\n特徵向量:\n',v)

特徵值:
 [13.  2.] 
特徵向量:
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [4]:
#3. 運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)
u,s,vh

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))

In [11]:
#請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。
Z = np.random.randint(0, 100, 1000000).reshape(100, 100, 100)
for i in Z:
    for j in i:
        for k in j:
            i = i + 1

#如何從一個陣列中，找出出現頻率最高的數值與位置？
X = np.random.randint(0,100,50)
print(X)

rint = (np.bincount(X).argmax())
rint

np.where(X == rint)[0] #where找尋位置




[33 64  9 72 97 67 46 64 51 51 23 27 55  3 51  3 11  7 77 35 51 12 52 90
 16  0 83 97 16 59 98 19 48  3 50 77 15  2 83 90 61 99  1 66  5 72 96 35
  7 93]


array([ 8,  9, 14, 20], dtype=int64)

In [13]:
#如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))




[3, 8, 2, 8, 3, 9]
[3, 8, 2, 8, 3, 9]
